import StoreProvider from '@/redux/StoreProvider';
import './globals.css';
import { Toaster } from 'sonner';

export const metadata = {
  title: 'Trello',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' data-theme='light'>
      <body className=''>
        <StoreProvider>
          <Toaster richColors closeButton />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
